### ISSUE TITLE
Unused param jobId in Repeat .removeRepeatable()

### ISSUE THREAD

**Issue by polRk** [taskforcesh/bullmq#111]
https://github.com/taskforcesh/bullmq/blob/b4a7dfd5691f35b67ce0474169bc02e31431e262/src/classes/repeat.ts#L91

**Comment by shivagoud** [comment]
I would like to take this up and fix. I was also confused when I was going through the code. Since the documentation isn't ready yet, it makes it much more difficult to follow.  Can you help me understand why it's there and what is it's original purpose @polRk @manast @stansv ?

**Comment by polRk** [comment]
I confused too,  when I was going through the code. Perhaps this remained after the transfer from version 3? 
My recommendation is to configure eslint and remove unsupported tslint from the project.

**Comment by santhosh77h** [comment]
@polRk @shivagoud @manast @stansv  I think JobId is required so whenever if we schedule two repeatable jobs at the same time and want to remove only one Job so we pass that JobId and delete only that Job but the functionality of it is not implemented...


this just my guess because when I started working on this I need the above feature for my work.

will this type of functionality is implemented or it's all my guesses.

**Comment by manast** [comment]
The new API removes this kind of awkwardnesses: https://docs.bullmq.io/guide/job-schedulers
