### ISSUE TITLE
Feature Request: Allow to using redis connection URL to connect directly.

### ISSUE THREAD

**Issue by cnwangjie** [taskforcesh/bullmq#1220]
The `ioredis` can accept redis connection URL on the constructor parameter. But it seems the bullmq can only accept the redis options only.

I knew that I can create a redis instance before and pass it to the connection opt, but it is better to accept the redis connection URL directly.

**Comment by ChrisLahaye** [comment]
What is important to note is that when you pass an existing connection, that bullmq won't use that connection directly but instead duplicates it. You will now have to close both connections to gracefully exit.

A better option would be to pass connection options instead of a connection, so that bullmq manages all connections. This will allow you to gracefully exit by just closing queue (which will close the underlying connection).

When using a redis connection URL you are pushed towards the first option of passing an existing connection as ioredis is able to parse these URLs, this is contrast to bullmq.

I recommend to parse the redis connection URL manually and pass connection options to bullmq so that all the connections are properly managed by bullmq.

You could use the following util:

```ts
import { URL } from 'url';
import type { RedisOptions } from 'ioredis';

export function parseUrl(input: string): RedisOptions {
  const url = new URL(input);

  const options: RedisOptions = {};

  if (url.hostname) options.host = url.hostname;
  if (url.port) options.port = parseInt(url.port);
  if (url.username) options.username = url.username;
  if (url.password) options.password = url.password;
  if (url.pathname.length > 1) options.db = parseInt(url.pathname.slice(1));

  return options;
}
```

**Comment by manast** [comment]
@ChrisLahaye thanks for the suggestion. I am not sure parsing the string ourselves is a good idea, as it is easy to miss something that ioredis would have used, so if we implement this it would be better to just send the string directly to ioredis.

**Comment by ChrisLahaye** [comment]
> @ChrisLahaye thanks for the suggestion. I am not sure parsing the string ourselves is a good idea, as it is easy to miss something that ioredis would have used, so if we implement this it would be better to just send the string directly to ioredis.

I fully agree with you but currently that is not possible.

**Comment by Thore1954** [comment]
This was already implemented in the old package:
https://github.com/OptimalBits/bull/blob/64672af9a59ece5e5cdb97e192a7824de72b48e1/lib/queue.js#L317-L339
Why not copy paste it in the new package?

**Comment by manast** [comment]
Actually, I am reluctant to backport Bull's handling of connection settings as it is quite messy. One of the goals of BullMQ is to have a cleaner implementation. So if you need to use a Redis string you can do as I do normally which is super easy and convenient:
```ts
const connection = new Redis("myredis.connection.string");
const queue = new Queue("myQueue", { connection });
```

Just remember to close the connection when you close the queue:

```ts
await queue.close();
await connection.close();
```

**Comment by manast** [comment]
Nevertheless, if somebody provides a PR with a simple elegant implementation I will not have any issue in merging it.

**Comment by Thore1954** [comment]
@manast Not that convenient actually since you have to be careful about blocking options in some cases (e.g. `QueueEvents`).
It would be best if `ConnectionOptions` also includes connection string. Won't even be a breaking change.

**Comment by lukashroch** [comment]
> Nevertheless, if somebody provides a PR with a simple elegant implementation I will not have any issue in merging it.

@manast Would #2746  be a acceptable solution for being able to use connection URL?
