### ISSUE TITLE
Worker keeps handles open after calling close()

### ISSUE THREAD

**Issue by fredgreer** [taskforcesh/bullmq#1312]
I am seeing open handle warnings from Jest when creating (and closing) BullMQ workers in an integration test:

```
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```

A minimal reproduction of the issue is:

```
import { Worker } from "bullmq";

describe("BullMQ worker", () => {
  it("leaves handles open after awaiting close()", async () => {
    const worker = new Worker("queue-name", async (job) => {}, {
      connection: {
        maxRetriesPerRequest: null,
      },
    });
    await new Promise((res) => setTimeout(res, 100));

    await worker.close();
  });
});
```

Interestingly the issue does not occur with the `setTimeout()` call removed.

- BullMQ version:  1.86.4
- jest version: 28.1.2
- ts-jest version: 28.0.5

I've uploaded the full reproduction here: https://github.com/PropellerAero/bullmq-open-handle-bug-repro

**Comment by MeoMix** [comment]
Heyo. Just chiming in that I also experience this issue. I spent a good amount of time trying to track down what was happening in the BullMQ source before finding this open ticket.

I have one QueueScheduler, one Worker, and no jobs. I have no issues with tearing down QueueScheduler, but I do have issues with tearing down my Worker.

If I add a generous wait after teardown, all is good:

```
  async function stop() {
    if (worker) {
      await worker.close();
      await workerRunPromise;
      console.debug(`STOP: Worker for ${queue} isRunning: ${worker.isRunning()}`);
    }

    await queueScheduler.close(true);
    await queueSchedulerRunPromise;
    console.debug(`STOP: QueueScheduler for ${queue} isRunning: ${queueScheduler.isRunning()}`);

    await new Promise((resolve) => setTimeout(resolve, 1000));
  }
  ```
  
  but if I remove the timeout - Jest complains.
  
Digging through the source a bit, I was able to track it down to the processing loop:
  
  ```
                      const processing = (this.processing = new Map());
                    while (!this.closing) {
                        if (processing.size < this.opts.concurrency) {
                            const token = (0, uuid_1.v4)();
                            processing.set(this.retryIfFailed(() => this.getNextJob(token), this.opts.runRetryDelay), token);
                        }
                        /*
                         * Get the first promise that completes
                         */
                        const promises = [...processing.keys()];
                        const completedIdx = await Promise.race(promises.map((p, idx) => p.then(() => idx)));
                        const completed = promises[completedIdx];
                        const token = processing.get(completed);
                        processing.delete(completed);
                        const job = await completed;
                        if (job) {
                            // reuse same token if next job is available to process
                            processing.set(this.retryIfFailed(() => this.processJob(job, token, () => processing.size <= this.opts.concurrency), this.opts.runRetryDelay), token);
                        }
                    }
                    this.running = false;
                    return Promise.all([...processing.keys()]);
```

If I break the functionality by changing to:

```
processing.set(new Promise((resolve) => setTimeout(resolve, 2000)), token);                         
```

then all is good.

It doesn't have to do with `retryIfFailed`. If I change the logic to

```
processing.set(this.getNextJob(token), token);
```

jest continues to complain.

If I edit `getNextJob` and remove the call to `waitForJob` (which was returning an undefined jobId anyway because I have no jobs to process) then Jest does not complain:

```
        if (this.drained && block) {
            try {
                const jobId = undefined; // await this.waitForJob();
                console.log('jobId', jobId);
                return this.moveToActive(token, jobId);
            }
```

and then, sure enough, if I force `jobId` to be undefined rather than awaiting `brpoplpush` - Jest does not complain:

```
jobId = undefined;
// jobId = await client.brpoplpush(this.keys.wait, this.keys.active, blockTimeout);
```

So my naïve interpretation of things is that the tear down process of a worker is leaving an unmanaged promise against a blocking connection to redis, but I didn't surface any issues in BullMQ's logic that would introduce a promise not being awaited. I thought it'd be somewhere with the `Promise.race` in `run`, but I didn't turn up anything.

Hope this helps. Thanks for the software.

**Comment by MeoMix** [comment]
My above solution no long appears to work after upgrading major version of BullMQ (to 2.x)

Exploring why this no longer works now.

**Comment by wezooyuri** [comment]
@MeoMix did you ever find a solution or workaround to this issue? I have seemingly ran into it as well today altough it's hard to be certain. Will update tomorrow with more details.

**Comment by MeoMix** [comment]
@wezooyuri Unfortunately the project I was on which involved BullMQ was cancelled shortly after these posts. So, I don't have additional information for you.

**Comment by wezooyuri** [comment]
@roggervalf Just a heads up, we still seem to experience this issue using jest without `--forceExit`. It might be interesting to create a test with an actual Redis connection, since it doesn't seem to be caught by the regular tests?

**Comment by clintonb** [comment]
I still see this issue nest-bullmq. I recently increased the `afterAll` timeout for my tests from 15s to 30s because it seems app/queue closing takes ~18s _despite the fact that Redis is mocked by ioredis-mock_. Something is still amiss here within BullMQ.
