### ISSUE TITLE
How do I safely move an active job back to the delayed queue?

### ISSUE THREAD

**Issue by kylecannon** [taskforcesh/bullmq#1340]
Hello,

First off thank you for the awesome library. I have a use case where a job that is active might need to be delayed until a further time. Is there a way to stop execution of the job and move it back to the delay queue? I see `job.moveToDelayed()` but it says that it will only work when the job is not active.

Thank you!

**Comment by roggervalf** [comment]
hi @kylecannon, this is a similar case as step jobs pattern https://docs.bullmq.io/patterns/process-step-jobs, you could use moveToDelayed method and pass the token from the worker to it

**Comment by MatthiasKunnen** [comment]
Relates to #643.

**Comment by roggervalf** [comment]
With my previous comment, I think this issue should be solved

**Comment by manast** [comment]
@happyhunter7 do you get this error when calling which method?

**Comment by happyhunter7** [comment]
@manast 
It appears when calling `moveToDelayed` ... the job indeed is moved but such error is logged
But I was able to resolve the issue it seems that after calling the `moveToDelayed` I have to throw a `DelayedError` nd then this error with `Error: Missing lock for job` does not appear
The documentation is a bit mistaken and if you take a look at the example you'll see that https://docs.bullmq.io/patterns/process-step-jobs DelayedError is thrown not in same switch-case statement that's why is confusing and I think the example should be udated

**Comment by manast** [comment]
@happyhunter7 yes, it seems that the example is incorrect actually, we will fix it asap.
