### ISSUE TITLE
Mocking Redis isnt supported anymore

### ISSUE THREAD

**Issue by Inoir** [taskforcesh/bullmq#1471]
Mocking redis in development mode was possible.
https://github.com/taskforcesh/bullmq/issues/86

Nowdays its not. Either the mock client doesnt have "options". if you fake it, ioredis-mock doesnt support "client" command.

Any way to bring back easy local development and also cloud testing?
Seems you guys create a real local redis connection on your tests?! This is not possible in many cloud systems.

**Comment by manast** [comment]
@Inoir I think the best would be to submit a PR to redis-mock so that it supports the stuff that is missing in order to be useful for testing BullMQ. If it is only something like the CLIENT command missing it should not be very hard to do.

We always use real Redis instances for testing, as this produces more trustworthy results.
