### ISSUE TITLE
Rate limiter with `max: 1` having unexpected results

### ISSUE THREAD

**Issue by wootwoot1234** [taskforcesh/bullmq#1565]
We are having issues when we set the rate limiter to:

```ts
limiter: {
    max: 1,
    duration: 100
},
```
It seems to be limiting the jobs more than it should.  It's taking much longer to move a job from `waiting` to `active` than 1 job every 100ms.

Also, when set it to:
```ts
limiter: {
    max: 1,
    duration: 1000/300 // 3.33333333333
},
```
it stopped processing jobs altogether.

Then in both cases, if we removed the rate limiter, it processed jobs immediately.

but after we use `duration: 1000/300`, if we add back the `duration: 100` limiter, it still didn't process jobs. The only way it would process jobs again was to remove the limiter completely.

We are running Redis version 6.2.6

Has anyone else been successful in setting the rate limiter to `max: 1`?

**Comment by manast** [comment]
Ok. I realized that PEXPIRE in Redis does not support floats: https://redis.io/commands/pexpire/
This means that the best accuracy we can get is milliseconds. I am adding a fix so that the duration gets floored to the closed millisecond, which in your case means that 3.33 will become 3, so it will process jobs a bit slower than the maximum allowed. Unfortunately, since Redis does not support better accuracy, I do not have a better solution ATM.
