### ISSUE TITLE
waitUntilFinished to be deprecated?

### ISSUE THREAD

**Issue by gabrielhase** [taskforcesh/bullmq#161]
We had a case in our code where a job, if it was processing fast, did never emit the `completed` event. Debugging the situation led us back to the constructor of `QueueEvents` that calls the async method `consumeEvents` which in turn awaits `this.client`.
The case we had was that our job (if it was running fast) was finished before `await this.client` returned thus the client wasn't ready yet to get data and the job was "lost" to the `completed` event.

Introducing `await jobQueueInstance.waitUntilFinished()` solved our problem. The problem now is that the method has the inconvenient label "to be deprecated" :) What is your intention to deprecate this method? And what would you suggest as a replacement?

In general, the calling of an async function from within a constructor seems to me an anti-pattern. The `catch` you have here https://github.com/taskforcesh/bullmq/blob/master/src/classes/queue-events.ts#L16 might even be a potential memory leak. Imagine the following code:
```
for (let i=0; i<100000; i++) {
  const queueEvents = new QueueEvents()
  delete queueEvents
}
```
If the promise holds a reference to the constructed object, the garbage collector might never clean up the `queueEvents` instances. I am not entirely sure about this (didn't test), but in any case it seems to be problematic if the object is de-constructed and then an error is caught in the de-constructed object from the promise.

For reference here is our code. With the addition of `await this.events.waitUntilReady()` it works fine now. But we are a bit concerned about the deprecation warning. Would be great if you could elaborate on that.

```
    async waitUntilFinished (job) {
      if (!this._initGlobalEvents()) return
      // NOTE: this method is "to be deprecated" in bullmq
      await this.events.waitUntilReady()
      if (job.then) job = await job
      return new Promise(async (resolve) => {
        const listener = (arg) => {
          resolve(arg.returnvalue)
          this.events.removeListener(`completed:${job.id}`, listener)
          this.events.removeListener(`failed:${job.id}`, listener)
        }
        this.events.on(`completed:${job.id}`, listener)
        this.events.on(`failed:${job.id}`, listener)
      })
    }

    _initGlobalEvents () {
      if (this.eventsEnabled === false) return false
      if (this.eventsEnabled) return true
      const connection = this.createClient()
      this.events = new QueueEvents(this.queueName, {...this.defaults, connection})
      this.events.on('error', (err) => { log.debug({err}, 'Job QueueEvents error') })

      const getterConnection = this.createClient()
      this.getters = new QueueGetters(this.queueName, {...this.defaults, connection: getterConnection}) // eslint-disable-line max-len
      connection.on('connect', () => { this.eventsEnabled = true })
      connection.on('close', () => { this.eventsEnabled = false })
      return true
    }
```

**Comment by noilda** [comment]
Thanks for the example. Finally I can see why my code is not working.

**Comment by manast** [comment]
I explain here why waitUntilFinished should not be used, https://blog.taskforce.sh/do-not-wait-for-your-jobs-to-complete/
It has not yet been deprecated, but maybe it will in the future.

**Comment by drone1** [comment]
Dear @manast: I'm just seeing your suggestion and article here and am hoping to get your thoughts on my endpoint system, if possible.

* My app has a web cluster and worker cluster. 
* Endpoints have multiple layers of caching. Browser / CDN / Redis, in that order.
* Endpoints are handled by the web cluster
* WebAPI's for GET requests have deterministic keys which are used to lookup any cached results in Redis
* If the result is not in Redis, the system looks to see if an existing job is already in flight to process the request.
* If there is no existing job, a job is enqueued for the worker cluster to handle. The web cluster will then await the result of this job (via `QueueEvents`, _not_  via `waitUntilJobFinished`). The worker cluster writes to the Redis cache.
* If there _is_ an existing job, the system will `waitUntilFinished`, so that if 1000 requests come in for the same API/params, only 1 will be processed and the others will wait for the result. 

If the 1 job fails, I'm in trouble. I can try to think about a better solution, but wanted to 1) pass along the data here to you here in case this is a common pattern you're seeing and it impacts any future articles you write, and 2) in case you do indeed already know of a more stable solution.

Thanks for your time.
