### ISSUE TITLE
Job is undefined in failed events.

### ISSUE THREAD

**Issue by ChoSeoHwan** [taskforcesh/bullmq#1629]
# ISSUE

When using the `removeOnFail:true` option, \
if failed due to stalled, \
the job is passed as undefined.

# TO BE

Must receive `job` object normally

# REPRODUCE

1. install `docker` to run `redis` container
2. clone my repository `https://github.com/ChoSeoHwan/bullmq-test.git`
4. `yarn install`
5. `yarn start:redis`
6. `yarn start`

## RESULT

```text
job pushing...
job pubshed : 6
accept 6
failed undefined Error : job stalled more than allowable limit
```

## Comment

The `lockDuration` and `lockRenewTime` settings in the `bullmq.mjs` script are options for forcibly reproducing the situation.\
In actual use, this option is not used.

## Repository

https://github.com/ChoSeoHwan/bullmq-test

**Comment by fillon** [comment]
A quick update.

V3.5.7 has fixed the issue for me.

**Comment by ChoSeoHwan** [comment]
The issue in this text also occurs in 3.5.10.

Since it is impossible to track the issue when stalled occurs, it seems that a quick fix is needed.

**Comment by manast** [comment]
I have been very late to the party but the issue here is basically that the job is being removed as soon as it failed (due to the setting ```removeOnFail: true```. This is a special case and basically there is no way to return the job in this case as the job has been removed already.  Also since "maxStalledCount" is set to 0, the job will fail directly, so no stalled event is generated.
One workaround for this case would be to use the class QueueEvents and listen to the global fail event, that event will return the actual jobId, still not the job itself, but a bit more of information. My recommendation here is to use a different setting for remveOnFail. Soon we are going to release telemetry support that will help into gaining more insights for this kind of issues.
