### ISSUE TITLE
Delayed jobs not trigerring every other launch

### ISSUE THREAD

**Issue by pavelserbajlo** [taskforcesh/bullmq#168]
Let say I'm scheduling a delayed task (10 seconds), which is normally getting triggered thanks to QueueScheduler listening. This works fine.

Now imagine I schedule the delayed task again, I quit the process and start it again, just so that it is ready before the job would trigger. But it never will, even though I can see in in queue.getDelayed().

I restart the app again an voila! Now it triggers it (since it probably found out it should have been triggered already).

Am I missing some config or anything else important? Thanks for any help.

**Comment by manast** [comment]
That sound strange, could you provide a small test case that demonstrate this problem so that I can take a look into it?

**Comment by matus123** [comment]
Hello,
i am having the same issue as OP. If i stop and immediately start application it behave the same way as mentioned above... but when i stop application and wait some time (30-60sec) and then start application.. everything works as excpected. 

I spent some time trying to figure out where might be problem. When it stops to work...
```
//readDelayedData function queue-scheduler.ts
data = await client.xread('BLOCK', blockTime, 'STREAMS', key, streamLastId);
```
always returns null

I am using these dependencies.
```
node: v13, v12
bullmq: 1.8.4
ioredis: 4.9.0

redis-docker: redis:5.0.7-alpine3.11
```
gist:
https://gist.github.com/matus123/824c8702efd2c75b02ca10c858bbc68f

**Comment by matus123** [comment]
If i create additional QueueSchedulers for each queue, it works even on immediate restarts.

@manast Is it okay to create multiple QueueSchedulers for queue ? Or should i expect some weird behavior ?

gist:
https://gist.github.com/matus123/7c9f7650d2dc707132e507de2f96dc32

**Comment by manast** [comment]
it is possible to have more than one for redundancy, but it should work with just one too.

**Comment by gWOLF3** [comment]
Exactly this. I am also having this issue. Copying from my other post

Delay is not working as expected: 

If I add delay field in this case, the job is never added back to the queue. It seems as though if the delay is called the worker does not get a new job event, even after the delay is over. 

When another job comes in, the worker does notice that there is the other job. In this case, the delay is rather irrelevant since it won't be processed regardless until another job hits the queue and triggers the event. This seems like not good behavior, bc there could be the case that, you add a job to a queue with a delay, and what happens if another job never comes in, then the job you added with the delay is lost forever. Either way something seems wrong here. 

code:
```
...
const worker = new Worker('Example', async job => {
console.log('hit job')
// process ....
  if (isNotReady) {
    await queue.add('job', { a: 'example' }, { delay: 5000 })
   console.log(`job not yet ready to be processed. added back to queue`)
  }
}
```
logs: 
```
hit job
job not yet ready to be processed. added back to queue.
job was completed
worker queue has been drained
```

**However** if I add the job back without a delay, it works as expected and the worker keeps iterating over the queue. It seems as though the delay field is somehow causing the job to never get added back to the queue. I've even tried with { delay: 1 }, and it still does not behave as expected.

**Comment by gWOLF3** [comment]
@pavelserbajlo Were you able to figure out a good workaround for this?

**Comment by pavelserbajlo** [comment]
I was evaluating if bullmq is stable enough for my needs and reported my findings here. Since it's not there yet, I'm patiently using bull instead :)

**Comment by lricoy** [comment]
I can confirm this happens to me as well but having more than one `QueueScheduler` appears to solve it. In my case it was not only for `delayed` jobs but if I restart the app when a long-running job is executing it was not being marked as "stalled" as well but would stay on the "active" state.

**Comment by PaulGrimshaw** [comment]
I confirm i had the above behaviour (repeated jobs not starting).  I have also seen problems with repeated jobs dropping out (no error, just not continuing, see above issue)

**Comment by manast** [comment]
I am looking into this...

**Comment by ifokeev** [comment]
the problem still exists with repeatable jobs

**Comment by ifokeev** [comment]
So as I see from issues and my own experience there is a BIG BIG problem with stalled jobs. That's hard to debug and understand what's going on and why it doesn't work. 

Now i'm having the issue with repeatable jobs which going stalled just when they launched. I tried different options for QueueScheduler, Worker, etc – no luck. Now that's the main reason to switch off `bullmq`

**Comment by manast** [comment]
@ifokeev do you have some code snippet that reproduces your issue?

**Comment by ifokeev** [comment]
@manast no, because I don't understand the issue really. I have `concurrency: 1` and about 6 queues with repeatable job (every 1 second, for example). It freezes randomly some of the queues or all of them. I tried to clean redis and different queue options, but no luck. I see only "stelled job" errors and `maxStalledCount` doesn't help. Looks like scheduler has some bugs inside.

**Comment by manast** [comment]
What are your jobs doing? stalled jobs happens when your processor is doing a long CPU intensive task.

**Comment by ifokeev** [comment]
@manast they are marked as stalled before running the real task so there are no CPU intensive tasks

**Comment by manast** [comment]
A job cannot be stalled until it is active, it is impossible. If you can provide some code we can look into it, I am afraid there must be some issue with your code.
