### ISSUE TITLE
Methodology for maintaining a set of repeatable jobs on deploy

### ISSUE THREAD

**Issue by rossmotley** [taskforcesh/bullmq#1709]
**Is your feature request related to a problem? Please describe.**

My app has a set of repeatable jobs. When it deploys I want to check to see if the currently-existing-in-the-queue repeatable jobs are the same as the ones the app currently specifies, and if they do not match, update them to match.

**Describe the solution you'd like**

A couple of approaches which could work:

* An option when adding a repeatable job which will delete any other jobs with the same name where the `repeat` options don't match.
* Provide a way to build the repeat key (eg. expose the internal `getRepeatKey(name, repeat)` function) so we can loop over `getRepeatableJobs()` and do it ourselves.

**Describe alternatives you've considered**

* Loop over all repeatable jobs, delete them all, and recreate them on every deploy.

**Comment by manast** [comment]
Yes, this is definitely an area we want to improve. I think that in order to improve the API regarding repeatable jobs we need to move out the repeatable settings from the standard jobs settings and create a new API for adding solely repeatable jobs. In this new API we could have options to identify a given repeatable job so that it is easy to examine, update or delete.

**Comment by manast** [comment]
With the new API ```upsertJobScheduler``` you should be able to achieve the requirements you listed above: 
https://docs.bullmq.io/guide/job-schedulers
