### ISSUE TITLE
Repeatable docs code example error

### ISSUE THREAD

**Issue by mgrahamx** [taskforcesh/bullmq#185]
Hi, it looks in your repeatable jobs section you have a coding error.

It says:

```
const myQueueScheduler = new QueueScheduler('Paint');
const myQueue = new Queue('Paint');

// Repeat job once every day at 3:15 (am)
await myQueue.add('submarine', { color: 'yellow' }, 
  {
    repeat: {
      cron: '15 3 * * *'
    }
  });

// Repeat job every 10 seconds but no more than 100 times
await myQueue.add('bird', { color: 'bird' }, 
  {
    repeat: {
      every: 10000,
      limit: 100
    }
  });
```

But this looks wrong, I think it should be `myQueueScheduler.add`.

**Comment by manast** [comment]
no, it is actually correct. QueueScheduler is the manager that takes care of "waking" up jobs that need to repeat. The reason to have it separately is because whereas you may have a lot of queue "adders" and workers, you only need one QueueScheduler (however is good to have 2 or 3 for redundancy in larger deployments)
