### ISSUE TITLE
Interest in taking over OpenTelemetry Instrumentation?

### ISSUE THREAD

**Issue by jenniferplusplus** [taskforcesh/bullmq#2048]
**Is your feature request related to a problem? Please describe.**
About a year ago I wrote an [opentelemetry auto-instrumentation](https://github.com/jenniferplusplus/opentelemetry-instrumentation-bullmq) library for BullMQ. I was at a company that made very active use of it, at the time. But I've changed jobs since then, and I don't keep up with this project anymore. Mostly that's fine, but it means that the instrumentation can get behind whenever BullMQ releases new major versions. And I'm not likely to know about it if a problem comes up in between then. As far as I'm aware, mine is the only auto-instrumentation for BullMQ that exists, which I'm sure isn't a great experience for teams that are trying to stay on a current version.

**Describe the solution you'd like**
Would you like to take over the project? I would be happy to deprecate my npm package and link to one that you publish as the BullMQ project instead. I could also provide some initial guidance on getting up to speed with the instrumentation, as-is.

**Describe alternatives you've considered**
Maintaining it hasn't been much of a burden, and I can keep doing it myself for as long as that's true. But I think it would be better for everyone if it's run by active contributors to BullMQ.

**Comment by manast** [comment]
@jenniferplusplus thank you for your efforts. If what you are asking is to integrate your module into BullMQ then the answer is that we are not interested, as we want to keep our module as lean as possible precisely to reduce the maintenance burden. Maybe there is some BullMQ user that would like to take the job of maintaining the module, so I can leave this issue open for a while to see if somebody wants to take the job.

**Comment by jenniferplusplus** [comment]
The instrumentation wouldn't need to be integrated into BullMQ itself. The common pattern with these auto-instrumenters is for them to exist as separate projects. But if you're not interested in taking over maintenance, that's fine. I'll keep doing it as I have time for it.

**Comment by manast** [comment]
What we can do is put a link in the README that points to your project and giving it more visibility.

**Comment by jenniferplusplus** [comment]
That's probably not necessary. People can find it, if they're looking. Thank you, though.

**Comment by patryk-smc** [comment]
Because of your open telemetry integration, I choose Bull in the first place. I don't understand how people can use it without it. I hope that you can find a maintainer as it's a bit disappointing that the Bull team doesn't seem keen on taking over.

**Comment by clintonb** [comment]
@manast what is the expectation around observability and production readiness for bullmq? Are folks expected to manually instrument every queue if they care about production readiness?

I am struggling to get https://github.com/jenniferplusplus/opentelemetry-instrumentation-bullmq working because the patching it, and similar libraries, rely on is not working. I've spent over an hour on this, and have no clue how much additional effort is required. My time, and that of others, could be saved if bullmq directly emitted OpenTelemetry spans and metrics, without patching.

**Comment by manast** [comment]
@clintonb what do you mean with patching? BullMQ has a comprehensive list of events, both global and local that can be used for instrumentation and debugging. We are not taking over a project for one particular vendor such as OpenTelemetry as we do not have the competence in the team to do this. I wish we had more resources but we have to prioritize based on what we have.

**Comment by jenniferplusplus** [comment]
@manast In JS, auto-instrumenters generally do some monkey patching to wrap their target library with methods that will build and populate spans. It's the standard practice in this ecosystem. OTel also isn't a vendor, it's a vendor neutral standard overseen by the CNCF. Not that this has to change anything for you.

@clintonb if there's a problem with the instrumenter, I can try to help. But the Bull team have been clear they're not going to handle OTel support themselves, so this probably isn't the right venue. I think this issue has outlived its usefulness, so I'm going to just close it.

**Comment by manast** [comment]
I am not sure but I do not think this uses monkey pathing: https://github.com/UpHabit/bull_exporter
Not sure why monkey patching is necessary considering you can hook to the events instead, but as mentioned I lack the knowledge in OpenTelemetry's SDK.

**Comment by clintonb** [comment]
@manast I took a quick look at the code for https://github.com/UpHabit/bull_exporter. I believe it works primarily by looking at the Redis queues, rather than instrumenting the actual library, hence no monkey-patching.

In my ideal scenario, bullmq directly emits OTel spans and metrics. The spans tell me how long each action (e.g., adding a job, consuming a job) is taking and aid with identifying and profiling slow processes. Metrics offer point-in-time information (e.g., number of jobs processed, number of failed jobs, execution time) that I can use to alert on specific conditions (esp. high error rate).

Yes, I _could_ subclass the worker and wrap `process()` in a span. I could also hook into the existing [events](https://docs.bullmq.io/guide/events) and [metrics](https://docs.bullmq.io/guide/metrics) to emit metrics. The problem is that _everyone_ who cares about this observability has to repeat this work, which may be a barrier to adoption for some.

OTel is a vendor-agnostic standard that has largely been adopted by various players and platforms in the observability space. Creating spans and emitting metrics is fairly straightforward. There are docs at https://opentelemetry.io/docs/instrumentation/js/libraries/#instrument-a-library-natively. I am happy to contribute to this effort, if your team is open to the idea.

**Comment by manast** [comment]
@clintonb I think there may be performance issues if spans are emitted for fast operations in BullMQ. Currently, the jobs keep some metric information (such as processing time, time in queue, etc) and it is also possible to enable the built-in metric system in BullMQ if time-series stats are required. For slow queues, it may be ok to enable telemetry that hooks into the internal methods of BullMQ, but for very fast queues that are processing thousands of jobs per second, I am afraid the telemetry itself is going to very much become a bottleneck. It would be better to examine the metrics produced by BullMQ standard operation in a pull fashion, instead of pushing data for every job that is added or processed by the queue...

**Comment by clintonb** [comment]
@manast that performance is a very valid concern that is addressed by https://opentelemetry.io/docs/concepts/instrumentation/libraries/#performance. Another alternative is to make usage of OTel optional via configuration.
