### ISSUE TITLE
Job autoremoval options per job type

### ISSUE THREAD

**Issue by sbruinsje** [taskforcesh/bullmq#2150]
**Is your feature request related to a problem? Please describe.**
When you add a job to a queue you can give options such as the number of completed or failed jobs to keep. I was surprised to find out that this amount of jobs to be kept is not for a specific job type but for all jobs.

**Describe the solution you'd like**
When adding a job like so: 
```
await myQueue.add('job-x', {}, { removeOnComplete: 10 })
await myQueue.add('job-y', {}, { removeOnComplete: 20 })
```
I'd like 10 job-x jobs to be kept and 20 job-y jobs to be kept. Where the current behaviour seems to be to use the options of the last added job for all jobs. At least that is what I am observing in my system.

**Describe alternatives you've considered**
I understand you probably don't want to touch the current behaviour. Maybe another queue method could be an option:
`await myQueue.setJobOptions(<jobName>, { removeOnComplete: 10 })`

**Comment by manast** [comment]
The problem here is that it is quite slow to determine the number of jobs of a given "name". All the completed jobs are stored in the completed set, so in order to know how many are of a different type we would need to traverse all the jobs, decode their names and count them, which would be too slow in many cases.

**Comment by sbruinsje** [comment]
Ah I see. 

In that case I feel its just a bit confusing that the queue.add() method offers a way to set global job options at all. The method gives off the idea that you're setting options for the thing that you are adding rather than for everything. But oh well, it is what it is, but maybe it can be made more obvious in the docs.

**Comment by nemphys** [comment]
+1, this is super confusing, it should either be changed to a queue-level property or renamed!

**Comment by manast** [comment]
@nemphys There is only one completed set, so the setting is for that set, not for a particular job name.

**Comment by manast** [comment]
This feature cannot be implemented in the current design, so closing it now.

**Comment by nemphys** [comment]
I totally understand, but maybe it should be at least documented properly in order to save people some time!

**Comment by manast** [comment]
@nemphys so please give me some feedback on what can be improved in the documentation as I think it is pretty clear: https://docs.bullmq.io/guide/queues/auto-removal-of-jobs

**Comment by nemphys** [comment]
@manast I suppose the confusing part is that the removeOnComplete/removeOnFail properties are part of each job's *addition* to the queue, implying that the setting only affects this specific job somehow (not the queue itself), as @sbruinsje also suggests above. This is not mentioned anywhere in the documentation.

Ideally, this setting should only be available at the queue level, since it defines/alters the global queue behavior regarding completed/failed job storage. If this is not possible/too big of a fuss, maybe stating something like "the setting affects the queue behavior for all subsequent job operations, regardless on job name" would be more descriptive of the situation.

**Comment by manast** [comment]
@nemphys I guess the expectations on what the API does or does not will always be a subject for debate. However, the documentation states super clearly how it works, and your suggestions for improvements are just redundant to what we already have:
![image](https://github.com/taskforcesh/bullmq/assets/95200/8ca08a2b-2b80-4429-a8fd-99bde37014e6)

![image](https://github.com/taskforcesh/bullmq/assets/95200/3d667fd9-6e90-49fb-8251-6a17b1a70723)

Furthermore, it seems like you are still not understanding how it works, it works as it is documented, so things like "the setting affects the queue behavior for all subsequent job operations, regardless on job name" are simply not true. The setting is applied when the job is completed, that's it, there is subsequent job operations or anything like that.

**Comment by nemphys** [comment]
OK, I will not argue further on this, just trying to be helpful here :-)
(it makes me wonder, though, since the creator of this issue seems to exactly share my view)
