### ISSUE TITLE
[Bug]: Excessive Redis polling when worker has high concurrency

### ISSUE THREAD

**Issue by urossmolnik** [taskforcesh/bullmq#2157]
### Version

4.8.0

### Platform

NodeJS

### What happened?

Workers with high `concurrency` can end up in state where they execute `getNextJob` X times for every new added job.
Where X is `concurrency` number.

This is causing excessive load on Redis. 

This can be remediated by lowering `concurrecy`, but there are use cases where we want to keep `concurrency` high to ensure few slow jobs don't block the queue.

### How to reproduce.

Have a worker with concurrency 100 and quick process function and push a job to worker's queue every 10ms.
BullMQ will end up executing >50k commands/seconds on Redis.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
Okay, so from what I can see when writing a test for this scenario, this is an edge case that happens if these two premises are fulfilled:
- There is a concurrency factor larger than 1.
- The queue does not have jobs normally, but they arrive one by one.

The reason this happens is due to the following:
When a worker starts, it checks if there are any jobs to fetch from the queue, if there aren't any, it will emit a BRPOPLPUSH command (only one), and that will keep the worker waiting until a job arrives in the queue. If the worker gets its BRPOPLPUSH completed and returns a job id, the worker will assume there are new jobs in the queue and it will try to fetch as many as possible based on the concurrency factor. If it happens to only an existing job, then yes, it will unnecessarily execute a bunch of Redis commands multiplied by the concurrency factor.

My take on this:
In most scenarios, this should not be a problem. If you have a busy queue, then the workers will not issue unnecessary commands. If the queue is not busy, and you still want to have a high concurrency factor, then there will be unnecessary commands issued but since the queue is not busy, it would not matter a lot since there will not be a performance issue.
Now, I don't see an easy way to solve this edge case without impacting other more common cases, since we want to have maximum performance when it matters the most (a lot of jobs and a lot of concurrency). For this to be solved, we would need to issue a slow sequential command after BRPOPLPUSH has returned and check if indeed there are more jobs after the last one or not, and only if there are more jobs, try to fetch them. But this is in general a bad solution, as you could have several workers running on different machines, and even if you know there are more jobs waiting, nothing could prevent other workers from actually picking up those jobs and leaving the remaining workers issuing commands unnecessarily.

The problem I guess is if you are using a service like Upstash, where they charge per command executed, unfortunately, there is no easy way to solve this issue  at this moment.
