### ISSUE TITLE
recommendedMinimumVersion redis for connect

### ISSUE THREAD

**Issue by mixassio** [taskforcesh/bullmq#2168]
Hello! what is the `recommendedMinimumVersion` constraint made for? what features of bullmq won't work with earlier versions?
This param use [here](https://github.com/taskforcesh/bullmq/blob/5acb79f063ba539743d0e9b508e5403e453ee094/src/classes/redis-connection.ts#L184) 

```
if (
        isRedisVersionLowerThan(
          this.version,
          RedisConnection.recommendedMinimumVersion,
        )
      ) {
        console.warn(
          `It is highly recommended to use a minimum Redis version of ${RedisConnection.recommendedMinimumVersion}
           Current: ${this.version}`,
        );
      }
```

**Comment by roggervalf** [comment]
hi @mixassio, we are supporting from v5 to v7, but the recommended version is 6.2.0 because there are some commands that we are differentiating depending on the redis version that is used, for example https://github.com/taskforcesh/bullmq/blob/master/src/classes/worker.ts#L540-L544, we recommend from v6.2.0 because it should work with the last improvements of our commands

**Comment by manast** [comment]
@mixassio previous to version 6.2 the blocking commands in Redis did not support float numbers for the timeout parameter. Since we rely on the timeout parameter for waiting to the next rate-limited or delayed job, in versions prior to 6.2 it will be less accurate, up to 1 second in extra delay.
