### ISSUE TITLE
[Bug]: groupKey in docs and Bull, not in BullMQ

### ISSUE THREAD

**Issue by ivnnv** [taskforcesh/bullmq#2269]
### Version

4.12.9

### Platform

NodeJS

### What happened?

[Docs](https://github.com/OptimalBits/bull/blob/583140e78a53ab9cb983e594b3db1ab95f79759e/REFERENCE.md?plain=1#L92) and [code](https://github.com/OptimalBits/bull/blob/583140e78a53ab9cb983e594b3db1ab95f79759e/lib/queue.js#L1370) for Bull have references for `groupKey`, but although  [it is referenced] in the docs (https://github.com/taskforcesh/bullmq/blob/719ba5bc6fcc09d99a664b8986bad67163bfcb90/docs/gitbook/guide/rate-limiting.md?plain=1#L51), theres no implementation on BullMq.

### How to reproduce.

Trying to set up `groupKey` on a Worker throws a TS error: `Type '{ groupKey: string; }' is not assignable to type 'RateLimiterOptions'.` 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
Please check the relevant documentation: https://github.com/taskforcesh/bullmq/blob/master/docs/gitbook/guide/rate-limiting.md

**Comment by ivnnv** [comment]
hi @manast, thanks for the pointer but what about if I dont want to define a hard global limit but different limit per queue or "logical group of queues"?
For example:
I can easily have 1000 jobs running at the same time, but I can only have 100 running per-second hitting different 3rd party services because they will reject me if I try to >100 each x time (this is just an example to illustrate the needed).
So this was easily achiveable with groupKeys, this is not possible anymore?

**Comment by manast** [comment]
It was not really achievable with groupKeys because the implementation was broken. It created a lot issues on the global rate limit as well, so once we got rid of it the code was simpler and more robust. For groups support on the other hand we provide the functionality in BullMQ Pro. Note that this library uses a completely different approach that is both robust and scales pretty well. You can read more here: https://docs.bullmq.io/bullmq-pro/groups
