### ISSUE TITLE
document still so poor 

### ISSUE THREAD

**Issue by skyblue** [taskforcesh/bullmq#246]
need more docs,  please.

**Comment by pruthvirajjadhav1** [comment]
Ya, I need it, these are one of the shittest docs I ever see. I love bullmq but there are no resources to refer to and the docs only contains some basic stuff. You need to work on improving some good docs.

**Comment by manast** [comment]
Thanks for the kind words.
Here some tutorials that covers basic and advanced topics: https://blog.taskforce.sh/
Stardard documentation: https://docs.bullmq.io/
API: https://api.docs.bullmq.io/

Btw, it is much more constructive to add specific hints on what should be improved instead of just bashing it as crap. Many many hours have been spent in creating these documents for your convenience.
