### ISSUE TITLE
Add event after job exhausted attempts

### ISSUE THREAD

**Issue by sfratini** [taskforcesh/bullmq#2616]
**Is your feature request related to a problem? Please describe.**
Perhaps a better way to handle jobs that are done processing failed attempts

**Describe the solution you'd like**
Add an event to the workers or queues so when a job has no more attempts to execute, we can run a particular logic. 

**Describe alternatives you've considered**
Currently we are doing this, which maybe there is a better way (or proper way)
```
workerAnalytics.on('failed', (job, err) => {
        logger.error(`${job?.id} has failed with ${err}`);
        if ((job?.attemptsMade || 0) >= (job?.opts.attempts || 0)){
            logger.info(`Job ${job?.id} has reached the maximum number of attempts`);
            //Add to DLQ
        }
    });
```

**Additional context**
Our goal is that jobs that have exhausted the attempts, can be stored in a DLQ (and then possible a DB) so we can analyse them and either discard them or re queue them again. We did not want to create this as a bug, since it seems the above approach works. I was just wondering if this is the right approach or maybe there is something to be done here or a better approach.

**Comment by manast** [comment]
We support already an event for this: https://api.docs.bullmq.io/interfaces/v5.QueueEventsListener.html#retries_exhausted
Also, if you have retries enabled, a job will only appear in the fail status if it has consumed all of its retries (otherwise it would be delayed waiting for the next attempt), so basically by just getting the failed jobs you are getting the jobs that have consumed all the retries and you do not need to do anything else.

**Comment by sfratini** [comment]
Hey @manast  Thank you for the link and apologies for the delay. I could not have the time to sit and plat with it. As you said, indeed that works as well. However, it seems it only works if I instantiate the QueueEvents with the same name as the Queue or the Worker name. Based on the docs, I would have expect QueueEvents to run on ALL workers and queues. 

If indeed it needs the name to be the same as the worker, then what is the difference against just listening to events in the same queue/worker as we are doing now? Not sure I see the function of the QueueEvents. Or at least it does not seem to do what it says. 

To be clear. This works:

`const queueEvents = new QueueEvents(QueueName.ANALYTICS);
`
This does not:

`const queueEvents = new QueueEvents('ALL');
`

Code for the event. Nothing fancy:

```
queueEvents.on('retries-exhausted', ({jobId, attemptsMade}) => {
    logger.error('retries-exhausted', {jobId, attemptsMade});
})
```

And our queues:

```
const queueBaseOptions: QueueOptions = {
    connection: {
        host: getRedisHost(),
        port: Number(getRedisPort())
    },
    defaultJobOptions: {
        attempts: 3,
        backoff: {
            type: 'exponential',
            delay: 2000,
        },
    },
};

export const dlqQueue = new Queue<DQLJobData>(QueueName.DLQ, queueBaseOptions);
export const standardQueue = new Queue(QueueName.STANDARD, queueBaseOptions);
export const analyticsQueue = new Queue(QueueName.ANALYTICS, queueBaseOptions);
```

Unless we use the same queue name to instantiate the QueueEvents, it does not fire. So I dont see the difference on doing (beyond not having to do the logic ourselves):

```
workerAnalytics.on('failed', async (job, err) => {
    logger.error(`${job?.id} has failed on analytics with ${err}`);
    await dlqLogic(job, err);
});
```

I just want to be sure we are not missing any functionality we could use in QueueEvents. 

Thanks!

**Comment by roggervalf** [comment]
hi @sfratini, QueueEvents instances must be created per queueName, they are not global for all queues that you are creating. Also you may notice that there are many different events https://api.docs.bullmq.io/interfaces/v5.QueueEventsListener.html that are triggered internally in our lua scripts independently of Worker or Queue methods. In order to have a similar behavior in your worker instance for failed event, you can check if attemptsMade >= (attempts option)

**Comment by sfratini** [comment]
Hey @roggervalf  thank you so much for the confirmation. If you check the first message, that logic is what we actually were doing before, just checking the attempts and if over, send to a DLQ that just stores the entire message into a DB, so we can reprocess or check what happened. 

I was a bit confused in this case since the documentation mentions that with QueueEvents you can listen to all QueueEvents in one single place. That seems to be the main benefit, but isn't this the same as adding an event to the queue itself like we were doing? I am just not seeing the benefit directly. Of course I can see there are many more events which that could be one thing, just not sure if QueueEvents actually accomplishes that part. 

Either way, you can close this issue if you feel like it, it is more like a functionality question. Thank you so much for the library and the work you have been doing!

**Comment by manast** [comment]
@sfratini QueueEvents listens to all the events of a given queue. Worker and Queue can only listen to events produced by those instances. So if you have 100 workers and you want to listen to "exhaust-retries" for all the workers in a given place then you use QueueEvents, otherwise you can use the Worker class instead.
