### ISSUE TITLE
Question: List of redis permissions to use all bullMQ features ? 

### ISSUE THREAD

**Issue by lukas-becker0** [taskforcesh/bullmq#2809]
Hi everyone,

today I noticed that `queue.getWorkersCount()` / `queue.getWorkers()` do not work if the `CLIENT LIST` permission is missing.

Our redis provider changed the permissions of the managed redis instance with redis 7
and since then `queue.getWorkersCount()` does not work anymore due to the missing `CLIENT LIST` permission.

> ReplyError: NOPERM User MY_USER has no permissions to run the 'client|list' command

Everything else seems to work as expected though.

So I was wondering whether there is a list of redis permissions a user needs to use all bullMQ features ?

**Comment by manast** [comment]
This is a strange request in my opinion. If a Redis host provider does not support a given Redis command, then they are not 100% compatible with Redis, in this case I suggest finding another provider as they are many (most of them) that are 100% compatible. We cannot keep a list of all the commands that BullMQ uses just because some small number of vendors do not support Redis as they should. We care about compatibility and we work together with many Redis vendors and we in fact even run the test suite agains them to guarantee compatibility, such as Dragonfly, Upstash, Valkey, and obviously Redis itself.

**Comment by manast** [comment]
Btw, I would be open to have a table with a list of known vendors that fully support BullMQ.

**Comment by kblcuk** [comment]
@manast this isn't that much about redis host though, it's about permissions.
For instance we use redis deployed on redis.io (I guess that's pretty official redis host) with a user that uses default read-write acl, that looks like `+@all -@dangerous ~*`.

However upon connecting with bull we get 
```
NOPERM this user has no permissions to run the 'info' command or its sub-commands
```

So it would be nice to know that one needs full access to redis instance for bull to work.

**Comment by pheliperocha** [comment]
I ran into the same issue. Here's the minimal ACL that works for me:

`~bull:* +@read +@write -@dangerous +info +eval +evalsha +script`

This keeps the user locked to only BullMQ keys, blocks all dangerous admin commands, and then adds back the few things it actually needs (INFO + Lua scripting). Everything has been running fine with this setup
