### ISSUE TITLE
[Feature Request] addBulk use lua script instead of redis transction

### ISSUE THREAD

**Issue by daimalou** [taskforcesh/bullmq#2824]
Redis transction is a fake transction, doesn't follow database ACID.

when addBulk 5 jobs, if 4st job fail, it doesn't rollback.

**Comment by manast** [comment]
@daimalou it is using Redis multi/exec which is all or nothing, so it is indeed a transaction. Can you provide a test case where this does not hold?

**Comment by daimalou** [comment]
nestjs real code

```ts

      const newimages = images.map((item, index) => {

        if (index !== 3) {
          return {
            name: 'aaa',
            data: item,
          };
        } else {
          // return unexpected data,  let  4th job error
          return 'rrrttttttttttttttttt'
        }
      });

      const job = await this.faceQueue.addBulk(newimages);
      console.log('bulkjob', job);

// but in worker
the 1st 2nd 3rd job is processing, it's not rollback.
```

it's redis part or bullmq

**Comment by manast** [comment]
That code you pasted is incomprehensible to me sorry...

**Comment by ccollie** [comment]
@daimalou to clarify, you're expecting transactional execution of multiple jobs added by `addBulk` (either all jobs succeed or execute a rollback) ? If so, that's not possible in BullMQ.

**Comment by manast** [comment]
@ccollie That would basically be equivalent to have just 1 job instead of a bulk of jobs. If you need to threat a bulk of jobs as 1 indivisible unit, then thats 1 job. Because it does not even make sense from the perspective of the job itself, even if you would be able to roll back the jobs, how would you roll up whatever the jobs have done? it just does not make any sense... I am closing as there is no issue here as far as I can see.

**Comment by daimalou** [comment]
@ccollie @manast 
i upload some code, need a redis connection,and go `http://localhost:3000/` in broswer, you will find the log.
https://github.com/daimalou/bullmqtest2

**Comment by manast** [comment]
Ok, I understand what you mean now. So In this case, one of the jobs instead of name and data it has gibberish and therefore the add script for that job will fail. I am not sure why you are sending gibberish, but basically of a Lua script fails like in this case, the multi/exec will not rollback. The failed script will be considered as it has been executed correctly. You must make sure that you are passing the correct arguments in order to avoid this issue.

**Comment by daimalou** [comment]
@manast OK,
I am simulating a scenario where I addbulk 1000 jobs. When 500 jobs have been added, Redis crashes for some reason. At this point, the 500 jobs have already been stored in Redis. I want to rollback.

**Comment by daimalou** [comment]
I asked GPT, it said
`Redis's MULTI/EXEC transaction essentially queues commands between MULTI and EXEC. If Redis crashes before reaching EXEC, all commands queued after MULTI will be lost, and the transaction will not be executed, effectively rolling back the transaction.`
OK, the issues is gone.
