### ISSUE TITLE
Question: dynamic queue isolation

### ISSUE THREAD

**Issue by loris** [taskforcesh/bullmq#303]
Hi @manast 
Quick question to get your insight on the following use-case:
Let's say I have a SaaS and use Bull to deal with jobs for thousands of customers. At one time, customer A makes an action which enqueue a large amount of jobs in Queue X. Those jobs are quite expensive, and the customer A jobs will take an hour to complete. A few minutes later, customer B makes another action, which also enqueue a large amount of jobs in Queue X.
Customer B jobs will remain in the waiting mode until all the customer A jobs are completed.

Do you recommend a better use of Bull or a mechanism i'm not aware of, which would allow customer B jobs to not "suffer" from customer A jobs.
As said, there are thousands of customers, so I'm not sure that statically creating one queue per customer is doable.
Thanks

**Comment by manast** [comment]
This is a very good question and a situation that is quite common. Currently there is not a perfect solution for this in BullMQ but I have been thinking about it in the past. Ideally what we want is some kind of "demux" where you connect multiple queues, potentially thousands of them and then you connect the workers to the demux consuming them in a round robin fashion, so that all customers get a fair share of the workers time. Implementation of this is not completely trivial but I see a big potential so maybe it will land on BullMQ in the future.
Workarounds for now, one would be to use a very large concurrency factor, if your jobs are IO intensive you can easily increase to 500 concurrency per worker, then you will consume many jobs in parallel and that could reduce the waiting time for customer B.
If your jobs are CPU intensive, then you will need to have more workers, maybe implement an automatic scaling depending on the amount of jobs waiting in the queue so that you use more workers when needed and go down when not needed, etc.

**Comment by loris** [comment]
Thanks! Interesting idea around the "demux" concept.
Regarding the workarounds, correct me if I'm wrong, but increasing concurrency or worker won't change the fact that customer A jobs will need to be all completed (because they were enqueued before, as in FIFO) before customer B jobs get processed, right? You just reduce the overall waiting time for customer B jobs?
I might have a shot on working on a user-land, simple implementation around the "demux" idea: splitting the Queue X in a small number of queues (let's say 5), and update the enqueueing code to have some logic where it will enqueue the large batch of customer B jobs in the "most empty" queue of the 5.

**Comment by manast** [comment]
> Regarding the workarounds, correct me if I'm wrong, but increasing concurrency or worker won't change the fact that customer A jobs will need to be all completed (because they were enqueued before, as in FIFO) before customer B jobs get processed, right? You just reduce the overall waiting time for customer B jobs?

yes, it will just mitigate the problem not resolve it.
