### ISSUE TITLE
Increasing connection and listener count

### ISSUE THREAD

**Issue by PaulGrimshaw** [taskforcesh/bullmq#336]
We are using sandboxed workers in BullMQ but are regularly getting "MaxListenersExceededWarning:" and also "ERR max number of clients reached".  Is there a way to reuse redis connection pool in a sandboxed job, or make sure that the connections get closed after each job run?  

Increasing limits just extends the time before we see the issues.

**Comment by manast** [comment]
MaxListenersExceededWarning is related to the number of listeners that you have setup, it is just a warning from nodejs so that you make sure you are not leaking listeners. As long as this number increases according to your expectations it can be ignored, but if it just keeps increasing and increasing over time it is probably a leak (I do not think the leak is in BullMQ though).
Regarding max number of connections to redis, the solutions are to either increasing the allowed number of connections or minimize the number of connections from your queues. There may be a leak in your code that is creating more connections than actually needed. If the number is correct, then you could try to reuse connections between queues as you suggested.

**Comment by jorgecuesta** [comment]
@manast exists some way to reuse a redis connection using sandboxes jobs?

**Comment by manast** [comment]
@jorgecuesta https://docs.bullmq.io/guide/connections

**Comment by jorgecuesta** [comment]
@manast I saw that, but neither is a sample for sandboxes, when you lunch sandboxes workers each "script" start a new connection because they run in a separate process.

**Comment by manast** [comment]
@jorgecuesta no because only the main process keeps the connection, the processes are only used to process the jobs.

**Comment by Steven-Chang** [comment]
This took me a long time to fix but I finally figured it out.
I had to do:
`
queue.disconnect();
`

`queue.exit();` did not work for me.
