### ISSUE TITLE
Repeated Job stops repeating

### ISSUE THREAD

**Issue by mxzinke** [taskforcesh/bullmq#393]
In my case, I have run a repeated job every 50 seconds. This one was now running for already 4 days straight. The job just stops and no one knows why. There was no error, no Redis flush, nothing. Even the second repeated job (also running every 50s and is in the same queue) still runs.

What I have to tell additionally, is that I run the jobs at 6 to 20 worker nodes (which also does other things), and all of them are trying to create the repeated job at the start of the application. The repeated jobs owning a queue for themselves.

**Comment by manast** [comment]
A repeatable job is a special job that adds a new delayed job upon processing, so it would be useful to know if there are any delayed jobs in your queue. This is easy to see using the api or you can use a UI such as https://taskforce.sh (with the trial is enough to do this investigation).

**Comment by nflorentin** [comment]
I just had the same issue with bullmq v1.6.7: a repeated job which worked well during 4 weeks and stop running after that. No error in logs. I don't know where the search for the error.

**Comment by manast** [comment]
@nflorentin as I mentioned before, can you take a look at the delayed jobs to see if there is a delayed job for the next repetition?

**Comment by nflorentin** [comment]
@manast I would like to but I am pretty beginner with Bullmq and I don't know how to do it without having to develop a script... Do you have a snippet for that ? 

I don't know if it can help but here is the code for my scheduled job:
```js
require('dotenv').config();

const connection = require('../services/redisConnection');
const Queue = require('bullmq').Queue;
const QueueScheduler = require('bullmq').QueueScheduler;

const queueScheduler = new QueueScheduler('defaultQueue', { connection });
const queue = new Queue('defaultQueue', { connection });


// clean all jobs before adding new ones
queue.getRepeatableJobs().then((repeatableJobs) => { 
  for(const job of repeatableJobs) {
    queue.removeRepeatableByKey(job.key).then(() => { 
      console.log(`previous job ${job.name} removed`); 
    }).catch((error) => {
      console.log(error);
    })
  }
  // add job import users
  if(process.env.IMPORT_USERS_CRON.length) {
    queue.add('import_users_job', {}, 
      {
        repeat: {
          cron: process.env.IMPORT_USERS_CRON,
          tz: process.env.TIME_ZONE,
        }
      }
    );
  }
}).catch((error) => {
  console.log(error);
});
```

**Comment by manast** [comment]
@nflorentin your code snippet above is wrong and could result in breaking the repeatable jobs.  You need to "await" for the promise returned by ```queue.removeRepeatableByKey``` otherwise you could be deleting the repeatable jobs that you are adding in the next ```queue.add``` call.
Having said that, you normally do not need to delete old repeatable jobs if you are adding the exact ones, adding an existing repeatable jobs is a no-op.

**Comment by nflorentin** [comment]
@manast thank you very much for your feedback. 

I followed your advice and removed the piece of code "remove old repeatable jobs" so the code is now much simpler and there is no more risk to delete the job.

I also install bull-bear to monitor the jobs, so I will come back here with more details the next time the problem happens.

**Comment by nflorentin** [comment]
@manast I think that it just happened again.

I restart the server at 7:52am, it runs the job directly (I don't know why) and it did not run at 8:00am which is strange because Bull-bear indicates that the job is delayed by 7 min so this seems correct. My cron expression is every hour (0 0 * * * *).

![Capture d’écran 2021-02-17 à 08 12 42](https://user-images.githubusercontent.com/5750349/108168850-3ba80700-70f8-11eb-9a54-e526a7aa4084.png)

**Comment by nflorentin** [comment]
I also noticed that the cron expression in the code snippet [in the documentation](https://docs.bullmq.io/guide/jobs/repeatable) seems wrong, it shows a format like that "15 3 * * *" but I could only make it worked with a format like "0 0 * * * *".  The [link to the cron-parser doc](https://www.npmjs.com/package/cron-parser) in the documentation shows a 6 * format.

**Comment by manast** [comment]
Thanks for pointing out the error in the documentation, it isI updated now.

**Comment by nflorentin** [comment]
@manast Just to report the problem with more details because it happened again today.
As you can see the last one that have been run was at 18:04 the 17th. 

![Capture d’écran 2021-02-18 à 08 01 38](https://user-images.githubusercontent.com/5750349/108318328-ee8f6800-71bf-11eb-81fe-654cc00d5483.png)
![Capture d’écran 2021-02-18 à 08 01 45](https://user-images.githubusercontent.com/5750349/108318338-f2bb8580-71bf-11eb-9e10-7810d59335c8.png)

**Comment by manast** [comment]
The screenshots are not so helpful, what we need is a test case that reproduces the issue. And as mentioned, is there a delay job for the next iteration of the repeatable job? and if so, what is the delay time? is it wrong?

**Comment by manast** [comment]
ok, sorry, I overlooked the screenshots. It looks correct, there is a delayed job for one hour as the cron specifies. That means your delayed job is not picked up and that could be that either your QueueScheduler or your Workers are not running or connected to the redis instance.

**Comment by nflorentin** [comment]
Exactly, you are right, the delayed job is simply not picked up.

In my docker container, I can see that my scheduler and my worker are running:
<img width="768" alt="Capture d’écran 2021-02-18 à 09 50 54" src="https://user-images.githubusercontent.com/5750349/108331273-e559c780-71ce-11eb-94e9-2b1a310814ac.png">

Here is the full code of the scheduler:
```javascript
require('dotenv').config();

const connection = require('../services/redisConnection');
const Queue = require('bullmq').Queue;
const QueueScheduler = require('bullmq').QueueScheduler;

const queueScheduler = new QueueScheduler('defaultQueue', { connection });
const queue = new Queue('defaultQueue', { connection });

queue.add('import_users_job', {}, 
  {
    repeat: {
      cron: process.env.IMPORT_USERS_CRON,
      tz: process.env.TIME_ZONE,
    }
  }
);
```

And the code of the worker:
```javascript
require('dotenv').config();

const connection = require('../services/redisConnection');
const Worker = require('bullmq').Worker;
const usersImport = require('../services/usersImport');
const usersCsvToDB = require('../services/usersCsvToDB');

const worker = new Worker('defaultQueue', async job => {
    if (job.name === "import_users_job") {
      usersImport.downloadUsersList(() => {
        usersCsvToDB.saveToDB(`./data/${process.env.SFTP_USERS_FILENAME}`);
      });
    }
}, {
  connection
});

worker.on('completed', (job) => {
  console.log(`${job.id} has completed!`);
});

worker.on('failed', (job, err) => {
  console.log(`${job.id} has failed with ${err.message}`);
});
```

I see no error in logs.

**Comment by nflorentin** [comment]
If I understand well, each time a repeated job is run, it enqueues the next one. 
Isn't that fragile ? I mean, if for any reason, the job is not run, then it will never be enqueue again ?

**Comment by manast** [comment]
No because the current job is only added if it succeeds adding the next iteration. In this case it did succeed so that is not the problem.
You can check if there are any workers actually connected to redis using https://github.com/taskforcesh/bullmq/blob/3a8873b6453405e6f8e57331f6cee30977406670/docs/gitbook/api/bullmq.queuegetters.getworkers.md

ex. ```ts
const workers = await queue.getWorkers();
```

Or using the command CLIENT LIST directly on redis: https://redis.io/commands/client-list

I expect your workers or schedulers have lost connection to redis.

**Comment by nflorentin** [comment]
@manast thank you for taking time to investigate that and help me.

I had to restart my app to make the job run because my app is in production and my clients are using it.
At the moment, the result of `queue.getWorkers()` is:
```javascript
 [
    {
      id: '5',
      addr: '172.30.0.4:40406',
      fd: '9',
      name: 'defaultQueue',
      age: '7257',
      idle: '2382',
      flags: 'N',
      db: '0',
      sub: '0',
      psub: '0',
      multi: '-1',
      qbuf: '0',
      'qbuf-free': '0',
      'argv-mem': '0',
      obl: '0',
      oll: '0',
      omem: '0',
      'tot-mem': '20616',
      events: 'r',
      cmd: 'evalsha',
      user: 'default'
    }
  ]
```

I will post again the result of `queue.getWorkers()` here as soon as the problem appears again.

**Comment by manast** [comment]
if you restart and it works again it is also a strong indication that it is loosing the connection. However it should re-connect if that happens, and also you should get some connection errors. Which version of BullMQ are you using?

**Comment by nflorentin** [comment]
Yes you right. I'm using 1.6.7, a bit old I admit. 
I can try to upgrade, although I would have liked to find the cause of the problem.

**Comment by nflorentin** [comment]
I upgraded to last version. I'll keep you updated.

**Comment by uh-vish** [comment]
Scheduled jobs stops without any error for me too.

**Comment by manast** [comment]
@uh-vish did you debug as explained above?

**Comment by uh-vish** [comment]
Will try this.

**Comment by mxzinke** [comment]
Just to make it clear for my described case:

I have multiple workers (around 4 to 10), this is not an issue. The connection was there. Also, I have 4 to 10 Queue-Schedulers (for redundancy), also they had connections all the time.

I changed the option `maxStalledCount` of the QueueScheduler to 0 and no job is disappearing. Maybe you can further investigate there.

**Comment by hsynlms** [comment]
I am new around here and your issue may be related to **using existing Redis connection** even for QueueScheduler

**What docs are saying:**

> Queue and Worker classes can accept an existing ioredis instance, and by that reusing that connection, however QueueScheduler and QueueEvents cannot do that because they require blocking connections to Redis, which makes it impossible to reuse them.

Possible related issue: https://github.com/taskforcesh/bullmq/issues/173

**Comment by nflorentin** [comment]
Just to keep you updated, no interruption of my repeated jobs since I upgraded to last version.

I keep an eye on it.
