### ISSUE TITLE
What's the scenario when the same job will be executed more than once? 

### ISSUE THREAD

**Issue by notgiorgi** [taskforcesh/bullmq#439]
From the [docs](https://docs.bullmq.io/what-is-bullmq):

> Exactly once queue semantics, i.e., attempts to deliver every message exactly one time, but it will deliver at least once in the worst case scenario*.

There's an asterisk in the end but I couldn't find an explanation, what's the scenario when the same job will be executed more than once?

**Comment by manast** [comment]
thats if your worker fails to keep the lock on the job till it completes (or fails it), so the job will become stall and processed by another worker.

**Comment by notgiorgi** [comment]
> thats if your worker fails to keep the lock on the job till it completes (or fails it), so the job will become stall and processed by another worker.

I'm not sure how'd this happen, can you elaborate? Do you mean if the job throws an exception/rejects?

**Comment by manast** [comment]
> I'm not sure how'd this happen, can you elaborate? Do you mean if the job throws an exception/rejects?

No. When a worker is processing a job it keeps a lock that expires by default every 30 seconds. If the job takes more time then that the worker will automatically extend the lock until the job completes (or fails). However if the worker for some reason do not extend the lock, for example if the process running the worker dies, then that job will become stalled and moved back to the wait list, and thus processed again in the future. There is a stalled limit setting though, if you set that to 0 (default is 1), then the job will fail instead of being moved back to wait.

**Comment by notgiorgi** [comment]
> > I'm not sure how'd this happen, can you elaborate? Do you mean if the job throws an exception/rejects?
> 
> No. When a worker is processing a job it keeps a lock that expires by default every 30 seconds. If the job takes more time then that the worker will automatically extend the lock until the job completes (or fails). However if the worker for some reason do not extend the lock, for example if the process running the worker dies, then that job will become stalled and moved back to the wait list, and thus processed again in the future. There is a stalled limit setting though, if you set that to 0 (default is 1), then the job will fail instead of being moved back to wait.

It's clear now, thanks!
