### ISSUE TITLE
Dynamically add childJobs while the main job is running

### ISSUE THREAD

**Issue by Haruki-Mortis** [taskforcesh/bullmq#599]
Maybe I missed it, but it would be awesome if it was possible to add childJobs to a job while it is running.

Example:
```typescript
const mainProcessor = async (job: Job) => {
  try {
    // do something
  } catch (error) {
    await job.addChild('errorProcessing', {error: error, parentId: job.id});
    throw error; 
  }
}
```

**Comment by roggervalf** [comment]
@Haruki-Mortis you can do it by using https://github.com/taskforcesh/bullmq/blob/master/docs/gitbook/api/bullmq.job.create.md that has JobOptions.parent https://github.com/taskforcesh/bullmq/blob/master/docs/gitbook/api/bullmq.jobsoptions.md, as I understand by your example, when you create that child, your parent job will not move to failed since you will have a pending child, at some point you would need to move your parent job to waiting children state https://github.com/taskforcesh/bullmq/blob/master/src/classes/job.ts#L801, there is a method to do this, but it is used on manual processing, you could use it but you should be aware that it will throw an error when the worker will try to move the parent job to failed or completed, then the parent job will be re-processed when the job is returned to active state. For now there is not an atomic way to manage this, but it is still in discussion about how to design it.

**Comment by Haruki-Mortis** [comment]
@roggervalf  Thank you very much for the answer.
It helps me a lot.
In my current case, I don't have to wait for the child to be processed.
In the first case it is important to see all child/parent jobs in the job information.
