### ISSUE TITLE
If QueueEventsOptions lastEventId is not set to `$`, it replays the full (all-time) event history on process restart

### ISSUE THREAD

**Issue by jbr** [taskforcesh/bullmq#76]
Possible solutions:
* Mark stream events as processed with [XACK](https://redis.io/commands/xack)
* Set the default lastEventId to `"$"` instead of `"0-0"`, only streaming new events. Downside of this approach: Events are ignored during QueueEvents listener unavailability

**Comment by stansv** [comment]
Hmm, I  thought we've already replaced `"0-0"` to `"$"` (https://github.com/taskforcesh/bullmq/issues/29)..

**Comment by jbr** [comment]
@stansv https://github.com/taskforcesh/bullmq/blob/master/src/classes/queue-events.ts#L29 is `0-0` and I don’t see any other redis commands than the XREAD

**Comment by jbr** [comment]
Would a PR that uses XREADGROUP be welcome?

**Comment by manast** [comment]
@jbr the code above regarding XTRIM is for internal delayed jobs events, 100 is a extremely safe value so that we do not need to rely on watchdogs as we had in Bull3.

Regarding QueueEVents, the workaround is to pass '$' to only receive new events. I thought I had changed that already but for some reason is not the default value yet.
