### ISSUE TITLE
Cannot obliterate non-paused queue

### ISSUE THREAD

**Issue by aislanmaia** [taskforcesh/bullmq#856]
Sometimes when trying to obliterate queue, we get the error: 
`Error: Cannot obliterate non-paused queue
`
I've noticed this often when trying to obliterate again the same queue after re-creating in the Redis.

Sometimes we're getting the error the first time using it.

One more thing is the key with `stalled-check` getting created into Redis and we don't have idea what this is coming from.

![Screenshot_20211103_185611](https://user-images.githubusercontent.com/2199137/140198670-4d930443-e2c7-4017-b177-3f43122551c0.png)

**Comment by manast** [comment]
@aislanmaia In order to guarantee that no running jobs are kept hanging after an obliteration, by default the queue is paused but will fail if there are active jobs on it. However (although not recommended) you can force away from this behaviour: https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueobliterate
But I thinking that the error message itself is wrong here, it should probably say "Cannot obliterate queue with active jobs in it"

**Comment by roggervalf** [comment]
In bullmq we have https://github.com/taskforcesh/bullmq/blob/master/src/classes/scripts.ts#L742

**Comment by roggervalf** [comment]
we have a test case that covers the error message https://github.com/taskforcesh/bullmq/blob/master/tests/test_obliterate.ts#L148-L150 mentioned above
